version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./sentense_bert:/workspaces/sentense_bert
    tty: true
    # command: cd /workspaces